[package]
name = "surge"
version = "0.1.0"
authors = ["Sevag Hanssian <sevag.hanssian@gmail.com>"]
description = "cli/daemon for music"
repository = "https://github.com/sevagh/surge"
readme = "./README.md"
license = "Apache-2.0"
keywords = ["music", "cli"]

[dependencies]

[profile.release]
debug = true
lto = true
panic = "abort"
